### ISSUE TITLE
Kojo's Punchlist

### ISSUE THREAD

**Issue by kojoidrissa** [vajda-lab/scc-api#38]
# Items/issues I need to resolve

## Django app/API code
- [x] Get BU to make the web apps use `https`
- [x] from `ftplus-dev`, when I run `docker-compose ps`, I get this error message: ```ERROR: Named volume "nfs-ftplus:/projectnb/ftplus:rw" is used in service "django" but no declaration was found in the volumes section.```
    - [x] Based on [Docker docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference) I think it can be resolved by adding a `volumes` section to the `docker-compose.yml` file. But since we're dealing with networked file systems, I feel like I should get a 2nd opinion.
- [x] new test for Token creation
- [x] change `sccApi` to `sccapi` or something better, throughout the app. I'll want Jeff's insight so I don't make it a bigger mess than it needs to be 🤣 😭 
- [x] Resolve issue w `scheduled_poll_job` and related test; Celery expects results to be JSON serializable
- [x] Update comments on `Job.status` states to distinguish b/w status in Django & status on SCC
    - [x] Ask Amanda about ERROR & COMPLETE, for clarity
- [x] Update comments on `submit_host_cli` commands to distinguish b/w actions in Django & on SCC
- [x] Review Jeff's "logging and dashboard" PR

### Original
- [x] Working w/ minimal test script Amanda gave me (SHOULD BE RESOLVED ONCE Container/Volume ISSUES RESOLVED)
    - [x] Make sure getting resulting TAR file back to Django app isn't an issue 
    - [x] Moving files 
        - [x] from local desktop to `kojo@ftplusdev` on the `ftplusdev` VM (DONE) and then
        - [x] to `ftsubmit@ftplus-dev` inside the `sge-submit-host` container  
- [x] Database soft-delete already implemented by `submit_host_cli.delete`. I need to sort out delete commands at the [API and Task](https://github.com/VajdaLab/scc-api/pull/39#issuecomment-825811034) level.
    - [x] Will be finalized once container/volume issues are resolved
- [x]  Look into adding `just` & a `Justfile` to Submit Host container, to simplify running some longer commands
    - [x] long command to start the container
    - [x] could allow Celery/`subprocess` to run `just {recipe}`
- [x] Configure SSH connect to Submit Host w/o typing password

### From #23 
- [x] The cli app should look for an API KEY or TOKEN which it will use to make API calls on behalf of the user. 
- [x] The TOKEN should be read from the environment <or> possibly from `~/.config/vajda` or some like-minded script
- [x] Figure out what tests the CLI app needs https://github.com/vajda-lab/scc-cli/issues/4
- [x] Make `status` instructions opt-out-able https://github.com/vajda-lab/scc-cli/issues/3
- [x] We might want our API_URL to default to the VajdaLab production server but allow us to update this for testing against a dev box. 

## Tasks code
- [x] Jeff's comment re: [creating SCC job directories](https://github.com/VajdaLab/scc-api/pull/40#discussion_r619262833)
## Other
- [x] Discuss container merge strategy & timeline w/ Jeff

## Jaime Questions (low-priority as of 2021-04-21)
- [x] `sge-submit-host` setup instructions seem to setup a VM, after I've SSHd into a VM?
- [x] `sge-submit-host` setup instructions led to repo being cloned into `/home/kojo`. Where will it actually be deployed?
- [x] Why 2 Dockerfiles: root & `c7`?
- [x] FILESYSTEM: is the `nfs-ftplus` filesystem mounted in the container shared w/ the SCC? Or is it a different filesystem? I need to make sure I know where code will have access.
    - [x] How do I make/delete directories and read the files from the SCC?
